### PR TITLE
News week homepage

### PR DESCRIPTION
**Pull request by ClaytonSiby**
The Newsweek Homepage feature branch is a replica of the NewsWeek.com.

* I created it using bootstrap 4 classes & grid system to position elements responsively on all screen sizes. 
* Sass Css played an important role to add more beauty &  style on the site.
* The site does not have the functionality to it, it is mainly focusing on strengthening development skills on the responsive design using frameworks ( in this case bootstrap ).

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @ClaytonSiby, great job with this project :+1:  Great commit messages :100: Let us improve our project and make it better. Let us address the comments below:
- ```Subscribe``` let us add the gray background so it looks like the clone. Images below will help us
``` Clone ```
addbg
```Source```
addbg1
- ```Sponsored Insight``` let us fix the width
``` Clone```
wide1
``` Source```
wide
``` Above the footer links``` let us fix the positioning of the social icons and the contents(heights, widths). Let us compare with the source
``` Clone ```
foy
``` Source ```
foy1
- Let us fix the spacing between the elements
``` Clone ```
mb
``` Source ```
mb1
-``` README ```
  - ```BUILT WITH```
    - The CSS name was repeated in the built with section
  - Add your email to the author section
- Kindly add files not related to the project to the gitignore file. Example .vscode

Kindly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by HADDADSOHAIB — CHANGES_REQUESTED** [review]
### Status: Change Required :recycle: 

### Hello @ClaytonSiby    :hand: 

### Good job your project is getting better and better. :+1: 

### Unfortunately, there are still some changes to get the project approved:
- This was asked bu the previous reviewer, I believe it is not fixed yet, I screen shot exactly what the previous reviewer asked:
Screenshot from 2020-06-17 11-27-57
Screenshot from 2020-06-17 11-28-11
- The newsletter, an image is missing:
your project:
Screenshot from 2020-06-17 11-32-57
Original:
Screenshot from 2020-06-17 11-33-41
- You should keep a professional repository, that includes removing unnecessary files:
Screenshot from 2020-06-17 11-34-55
- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))


### Once done with the requirements, please ask for another code review.

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @ClaytonSiby   :wave:
-
You have done a splendid job with the changes! :tada: Keep it up.
The site coming along just fine. We, however, do have some few changes to carry out before we proceed (see review comment).
##
This being a bootstrap project. We need to ensure nothing is messed up. Compare the differences below and work on the suggested changes. 

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/ClaytonSiby/Responsive-Web-Design-_The-NewsWeek/NewsWeek-Homepage/idesign/index.html)|
|:---:|:---:|
|source|clone|

- [ ] Work on the page's content's centring by increasing the margins on both sides in large screens.

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — COMMENTED** [review]
## Status: Approved :trophy: :balloon: 

Hi @ClaytonSiby, great job :+1: Thanks to your patience and desire to learn and improve, and with the help of our TSE's, our project now meets all the minimum requirements :smile: 

Go ahead and merge to master and submit the project completion form :+1: 
Good luck with your next projects :100: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
